name: OracleClientExtension Nuget Package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Build with dotnet
      run: dotnet build src/OracleClientExtension/OracleClientExtension/OracleClientExtension.csproj --configuration Release
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Pack with dotnet
      run: dotnet pack src/OracleClientExtension/OracleClientExtension.csproj --output nuget-packages --configuration Release
    - name: Push with dotnet
      run: dotnet nuget push nuget-packages/*.nupkg --api-key ${{ secrets.NUGET_DEPLOY_KEY }} --source https://api.nuget.org/v3/index.json
